version: '3.8'

services:
  db:
    image: postgres:16
    container_name: firmeza_db
    environment:
      POSTGRES_DB: firmeza_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwe.123*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./Firmeza.Web
      dockerfile: Dockerfile
    container_name: firmeza_web
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=firmeza_db;Username=postgres;Password=Qwe.123*
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - recibos_data:/app/wwwroot/recibos

volumes:
  postgres_data:
  recibos_data: